### ISSUE TITLE
hai,Neorg doesn't seem very stable

### ISSUE THREAD

**Issue by denstiny** [jubnzv/mdeval.nvim#4]

**Comment by denstiny** [comment]
![图片](https://user-images.githubusercontent.com/57088952/167625584-bbcfb754-9fb6-468a-ad11-2725354d1260.png)

This is a simple code is fast, but mdeval can't find it

**Comment by denstiny** [comment]
![图片](https://user-images.githubusercontent.com/57088952/169293413-83dcae81-2da2-44a8-bbb5-82f3ddfed9cd.png)


> a.norg
```
** test
   @code cpp
   #include <cstdio>
   #include <iostream>
   int main (int argc, char *argv[])
   {
     printf("hello world");
     return 0;
   }
   @end
```

**Comment by jubnzv** [comment]
Thanks! I fixed this.
