### ISSUE TITLE
Source code blocks' issues in Norg files

### ISSUE THREAD

**Issue by Srinath-Anand** [jubnzv/mdeval.nvim#6]
Python source code blocks produce `IndentationError`s if they're placed inside a Neorg heading.
This doesn't happen for some other code blocks (Lua and C++ that I tested)
![2022-10-28-101640_1920x1080_scrot](https://user-images.githubusercontent.com/71964994/198504710-45b4e46a-cdfa-466f-ba80-59b61cfd7567.png)

Python source code blocks also work properly if they're above all headings.

**Comment by jubnzv** [comment]
Hi @Srinath-Anand, thanks for the report.

Could you please attach the minimal reproducible example (i.e. the norg document with this source code)?

**Comment by Srinath-Anand** [comment]
* Main heading
      /Something/ inside the heading.
      Lua code block.
      @code lua
      -- Lua
      print('Hello')
      @end

*Results:* `Hello`
      Python code block.
      @code python
      # Python
      print('Hello')
      @end

*Results:*
@code
  File "/tmp/mdeval//MdEvalnorg_11_14.py", line 2
    print('Hello')
IndentationError: unexpected indent
@end

**Comment by Srinath-Anand** [comment]
A screenshot for file reference - I couldn't upload the `norg` document.
![2022-10-29-154932_1920x1080_scrot](https://user-images.githubusercontent.com/71964994/198826110-512bf4b3-80e5-4cff-a74a-886fc751097c.png)

**Comment by jubnzv** [comment]
Thanks!

It should be fixed by https://github.com/jubnzv/mdeval.nvim/commit/bd7fc0401927a7a6d91725b169acb12d7f3ee583.

**Comment by Srinath-Anand** [comment]
Can confirm that the issue's been fixed @jubnzv 
Thank you!
